INDEX_CONFIGS = [
    # usa
    {
        "name": "sp500",
        "region": "usa",
        "url": "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies",
        "table_id": "constituents",
        "table_index": 0,
        "symbol_col": "Symbol",
        "ticker_suffix": "",
        "expected_count": 503,
    },
    {
        "name": "nasdaq100",
        "region": "usa",
        "url": "https://en.wikipedia.org/wiki/Nasdaq-100",
        "table_id": "constituents",
        "table_index": 4,
        "symbol_col": "Ticker",
        "ticker_suffix": "",
        "expected_count": 100,
    },
    {
        "name": "dowjones",
        "region": "usa",
        "url": "https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average",
        "table_match": "Symbol",
        "table_index": 1,
        "symbol_col": "Symbol",
        "ticker_suffix": "",
        "expected_count": 30,
    },
    # ind
    {
        "name": "nifty50",
        "region": "ind",
        "url": "https://en.wikipedia.org/wiki/NIFTY_50",
        "table_match": "Symbol",
        "table_index": 1,
        "symbol_col": "Symbol",
        "ticker_suffix": ".NS",
        "expected_count": 50,
    },
    {
        "name": "niftynext50",
        "region": "ind",
        "url": "https://en.wikipedia.org/wiki/NIFTY_Next_50",
        "table_match": "Symbol",
        "table_index": 0,
        "symbol_col": "Symbol",
        "ticker_suffix": ".NS",
        "expected_count": 50,
    },
    # gbr
    {
        "name": "ftse100",
        "region": "gbr",
        "url": "https://en.wikipedia.org/wiki/FTSE_100_Index",
        "table_match": "Ticker",
        "table_index": 6,
        "symbol_col": "Ticker",
        "ticker_suffix": ".L",
        "expected_count": 100,
    },
    # eur [tickers already include exchange suffix]
    {
        "name": "eurostoxx50",
        "region": "eur",
        "url": "https://en.wikipedia.org/wiki/EURO_STOXX_50",
        "table_match": "Ticker",
        "table_index": 3,
        "symbol_col": "Ticker",
        "ticker_suffix": "",
        "expected_count": 50,
    },
    # deu [tickers already include .DE suffix]
    {
        "name": "dax40",
        "region": "deu",
        "url": "https://en.wikipedia.org/wiki/DAX",
        "table_match": "Ticker",
        "table_index": 4,
        "symbol_col": "Ticker",
        "ticker_suffix": "",
        "expected_count": 40,
    },
    # hkg [tickers formatted as "SEHK: 5"]
    {
        "name": "hangseng",
        "region": "hkg",
        "url": "https://en.wikipedia.org/wiki/Hang_Seng_Index",
        "table_match": "Ticker",
        "table_index": 6,
        "symbol_col": "Ticker",
        "ticker_suffix": ".HK",
        "ticker_format": "sehk",
        "expected_count": 82,
    },
    # fra [tickers already include exchange suffix]
    {
        "name": "cac40",
        "region": "fra",
        "url": "https://en.wikipedia.org/wiki/CAC_40",
        "table_match": "Ticker",
        "table_index": 3,
        "symbol_col": "Ticker",
        "ticker_suffix": "",
        "expected_count": 40,
    },
    # can
    {
        "name": "tsx60",
        "region": "can",
        "url": "https://en.wikipedia.org/wiki/S%26P/TSX_60",
        "table_match": "Symbol",
        "table_index": 1,
        "symbol_col": "Symbol",
        "ticker_suffix": ".TO",
        "expected_count": 60,
    },
    # aus
    {
        "name": "asx50",
        "region": "aus",
        "url": "https://en.wikipedia.org/wiki/S%26P/ASX_50",
        "table_match": "Symbol",
        "table_index": 0,
        "symbol_col": "Symbol",
        "ticker_suffix": ".AX",
        "expected_count": 50,
    },
    # che
    {
        "name": "smi",
        "region": "che",
        "url": "https://en.wikipedia.org/wiki/SMI_Expanded",
        "table_match": "Ticker",
        "table_index": 1,
        "symbol_col": "Ticker",
        "ticker_suffix": "",
        "expected_count": 20,
        "ticker_overrides": {
            "ROG.SW": "ROP.SW",
            "BALN.SW": "HBAN.SW",
            "HELN.SW": "HBAN.SW",
            "BEAM.SW": "BEAN.SW",
            "BKWB.SW": "BKW.SW",
        },
    },
    # esp
    {
        "name": "ibex35",
        "region": "esp",
        "url": "https://en.wikipedia.org/wiki/IBEX_35",
        "table_match": "Ticker",
        "table_index": 2,
        "symbol_col": "Ticker",
        "ticker_suffix": ".MC",
        "expected_count": 35,
    },
    # nld
    {
        "name": "aex",
        "region": "nld",
        "url": "https://en.wikipedia.org/wiki/AEX_index",
        "table_match": "Ticker",
        "table_index": 3,
        "symbol_col": "Ticker",
        "ticker_suffix": ".AS",
        "expected_count": 25,
    },
    # swe
    {
        "name": "omx30",
        "region": "swe",
        "url": "https://en.wikipedia.org/wiki/OMX_Stockholm_30",
        "table_match": "Ticker",
        "table_index": 1,
        "symbol_col": "Ticker",
        "ticker_suffix": ".ST",
        "expected_count": 30,
    },
    # sgp
    {
        "name": "sti",
        "region": "sgp",
        "url": "https://en.wikipedia.org/wiki/Straits_Times_Index",
        "table_match": "Stock symbol",
        "table_index": 3,
        "symbol_col": "Stock symbol",
        "ticker_suffix": ".SI",
        "expected_count": 30,
    },
    # bel
    {
        "name": "bel20",
        "region": "bel",
        "url": "https://en.wikipedia.org/wiki/BEL_20",
        "table_match": "Ticker symbol",
        "table_index": 2,
        "symbol_col": "Ticker symbol",
        "ticker_suffix": ".BR",
        "expected_count": 20,
        "ticker_overrides": {
            "APAM": "APAM.AS",
        },
    },
    # ita
    {
        "name": "ftsemib",
        "region": "ita",
        "url": "https://en.wikipedia.org/wiki/FTSE_MIB",
        "table_match": "Ticker",
        "table_index": 1,
        "symbol_col": "Ticker",
        "ticker_suffix": ".MI",
        "expected_count": 40,
    },
    # prt
    {
        "name": "psi",
        "region": "prt",
        "url": "https://en.wikipedia.org/wiki/PSI-20",
        "table_match": "Ticker",
        "table_index": 2,
        "symbol_col": "Ticker",
        "ticker_suffix": ".LS",
        "expected_count": 20,
        "ticker_overrides": {
            "SONC": "SNC",
        },
    },
    # jpn [components listed as {{tyo2|XXXX}} wikitext, no html table]
    {
        "name": "nikkei225",
        "region": "jpn",
        "url": "https://en.wikipedia.org/wiki/Nikkei_225",
        "ticker_format": "nikkei",
        "ticker_suffix": ".T",
        "expected_count": 225,
    },
    # fin [tickers already include .HE suffix]
    {
        "name": "omxhelsinki25",
        "region": "fin",
        "url": "https://en.wikipedia.org/wiki/OMX_Helsinki_25",
        "table_match": "Ticker",
        "table_index": 1,
        "symbol_col": "Ticker",
        "ticker_suffix": "",
        "expected_count": 25,
    },
    # nor
    {
        "name": "obx",
        "region": "nor",
        "url": "https://en.wikipedia.org/wiki/OBX_Index",
        "table_match": "Ticker symbol",
        "table_index": 1,
        "symbol_col": "Ticker symbol",
        "ticker_suffix": ".OL",
        "expected_count": 25,
    },
    # aut: the Austrian_Traded_Index wikipedia table has no ticker column [company + industry only]
    # atx is not added until a suitable source is found

    {
        "name": "sensex",
        "region": "ind",
        "url": "https://en.wikipedia.org/wiki/List_of_BSE_SENSEX_companies",
        "table_match": "Symbol",
        "table_index": 0,
        "symbol_col": "Symbol",
        "ticker_suffix": ".BO",
        "expected_count": 30,
    },
    # idn [tickers formatted as "IDX: ACES", colon-prefix stripping handles the prefix]
    {
        "name": "lq45",
        "region": "idn",
        "url": "https://en.wikipedia.org/wiki/LQ45",
        "table_match": "Ticker",
        "table_index": 1,
        "symbol_col": "Ticker",
        "ticker_suffix": ".JK",
        "expected_count": 45,
    },
    # dnk [class-share tickers like "NOVO B" normalized to "NOVO-B.CO" via space-to-dash]
    # actual column on the page is "Ticker symbol", not "Ticker"
    {
        "name": "omxcopenhagen25",
        "region": "dnk",
        "url": "https://en.wikipedia.org/wiki/OMX_Copenhagen_25",
        "table_match": "Ticker symbol",
        "table_index": 1,
        "symbol_col": "Ticker symbol",
        "ticker_suffix": ".CO",
        "expected_count": 25,
    },
    # isr
    {
        "name": "ta35",
        "region": "isr",
        "url": "https://en.wikipedia.org/wiki/TA-35_Index",
        "table_match": "Ticker",
        "table_index": 1,
        "symbol_col": "Ticker",
        "ticker_suffix": ".TA",
        "expected_count": 35,
    },

    # nzl
    {
        "name": "nzx50",
        "region": "nzl",
        "url": "https://en.wikipedia.org/wiki/S%26P/NZX_50_Index",
        "table_match": "Ticker symbol",
        "table_index": 1,
        "symbol_col": "Ticker symbol",
        "ticker_suffix": ".NZ",
        "expected_count": 50,
    },
    # irl [tickers formatted as "Euronext Dublin: A5G"]
    {
        "name": "iseq20",
        "region": "irl",
        "url": "https://en.wikipedia.org/wiki/ISEQ_20",
        "table_match": "MNEM code",
        "table_index": 0,
        "symbol_col": "MNEM code",
        "ticker_suffix": ".IR",
        "expected_count": 20,
    },
]
